// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/db/user": {
            "post": {
                "description": "create a user using post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DB Example API"
                ],
                "summary": "Create a user",
                "parameters": [
                    {
                        "description": "User object",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dbexample.UserCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/dbexample.UserGet"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/db/user/{name}": {
            "get": {
                "description": "Get a User by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DB Example API"
                ],
                "summary": "Get a User by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/dbexample.UserGet"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check for the health of the server",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Health Check"
                ],
                "summary": "Health check for the server",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sentry/crash": {
            "get": {
                "description": "Crash the server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sentry Test API"
                ],
                "summary": "Crashes the server and sends a report to Sentry",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/testing": {
            "get": {
                "description": "Redirects from the root URL to login or day page.",
                "tags": [
                    "Testing API"
                ],
                "summary": "Root URL redirections",
                "responses": {
                    "300": {
                        "description": "Multiple Choices"
                    }
                }
            }
        },
        "/testing/faces/login.jsp": {
            "get": {
                "description": "Login",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Testing API"
                ],
                "summary": "Login",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/testing/faces/secured/burza.jsp": {
            "get": {
                "description": "Burza",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Testing API"
                ],
                "summary": "Burza",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/testing/faces/secured/main.jsp": {
            "get": {
                "description": "Day",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Testing API"
                ],
                "summary": "Day",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/testing/faces/secured/month.jsp": {
            "get": {
                "description": "Month",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Testing API"
                ],
                "summary": "Month",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/testing/j_spring_security_check": {
            "post": {
                "description": "Security",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "tags": [
                    "Testing API"
                ],
                "summary": "Security",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username for login",
                        "name": "j_username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password for login",
                        "name": "j_password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF token",
                        "name": "_csrf",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "dbexample.UserCreate": {
            "type": "object",
            "required": [
                "age",
                "name"
            ],
            "properties": {
                "age": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dbexample.UserGet": {
            "type": "object",
            "required": [
                "age",
                "id",
                "name"
            ],
            "properties": {
                "age": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "API for testing that the database is setup correctly",
            "name": "DB Example API"
        },
        {
            "description": "Api for testing Sentry is setup correctly",
            "name": "Sentry Test API"
        },
        {
            "description": "Health Check for this API",
            "name": "Health Check"
        },
        {
            "description": "Endpoints that require authentication",
            "name": "Protected"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "APPE autojidelna example server",
	Description:      "This is an example for all api server projects in App Elevate",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
